# A -*- dockerfile -*- that builds the exchange office service into a smaller image
# Copyright (C) 2025  Arsen Arsenović <aarsenovic8422rn@raf.rs>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
FROM harbor.k8s.elab.rs/banka-4/python:3.13 AS build

RUN mkdir /code
ADD exchange-office/LICENSE /code/LICENSE
ADD exchange-office/pyproject.toml /code/pyproject.toml
ADD exchange-office/tests /code/tests
ADD exchange-office/banka4_exchange /code/banka4_exchange

RUN pip install flit

RUN cd /code \
    && FLIT_ROOT_INSTALL=1 flit install --only-deps --deps production \
    && flit build --format wheel \
    && mv dist/*.whl /


# Create a smaller production image
FROM harbor.k8s.elab.rs/banka-4/python:3.13

COPY --from=build /*.whl /
RUN pip install gunicorn /*.whl && rm -f /*.whl

RUN mkdir -p /work /usr/var/banka4_exchange/
COPY docker/exchange-config.py /usr/local/var/banka4_exchange-instance/config.py

VOLUME /data
ENTRYPOINT ["gunicorn"]
CMD ["-b", "0.0.0.0:8000", "banka4_exchange.wsgi:app"]
