# A -*- dockerfile -*- that builds a Java service and deploys its .jar in a
# smaller image
# Copyright (C) 2025  Arsen Arsenović <aarsenovic8422rn@raf.rs>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM harbor.k8s.elab.rs/base-images/base:gradle-21-node-22-docker AS build

RUN mkdir /code

ADD gradle /code/gradle
ADD testlib /code/testlib
ADD buildSrc /code/buildSrc
ADD common /code/common

ADD gradle.properties /code/
ADD settings.gradle.kts /code/
ADD build.gradle.kts /code/

ARG SERVICE
ADD ${SERVICE} /code/${SERVICE}

WORKDIR /code
RUN gradle --build-cache --no-daemon :"${SERVICE}":bootJar

FROM harbor.k8s.elab.rs/banka-4/eclipse-temurin:21-jre

ARG SERVICE
COPY --from=build \
    /code/"${SERVICE}"/build/libs/"${SERVICE}"-0.0.1-SNAPSHOT.jar \
    /service.jar

RUN mkdir /work
WORKDIR /work
ENTRYPOINT ["java", "-jar"]
CMD ["/service.jar"]
