CREATE TABLE client_linked_accounts
(
    client_id      VARCHAR(255) NOT NULL,
    linked_account VARCHAR(255)
);

CREATE TABLE clients
(
    id              VARCHAR(255) NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    date_of_birth   date         NOT NULL,
    gender          VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    phone           VARCHAR(255) NOT NULL,
    address         VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    enabled         BOOLEAN      NOT NULL,
    permission_bits BIGINT       NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id              VARCHAR(255) NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    date_of_birth   date         NOT NULL,
    gender          VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    phone           VARCHAR(255) NOT NULL,
    address         VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    enabled         BOOLEAN      NOT NULL,
    permission_bits BIGINT       NOT NULL,
    username        VARCHAR(255) NOT NULL,
    department      VARCHAR(255) NOT NULL,
    position        VARCHAR(255) NOT NULL,
    active          BOOLEAN      NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE tokens
(
    id    VARCHAR(255) NOT NULL,
    token VARCHAR(255),
    valid BOOLEAN,
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

CREATE TABLE verification_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255),
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    used            BOOLEAN                                 NOT NULL,
    email           VARCHAR(255),
    CONSTRAINT pk_verification_tokens PRIMARY KEY (id)
);

ALTER TABLE clients
    ADD CONSTRAINT uc_clients_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_username UNIQUE (username);

ALTER TABLE tokens
    ADD CONSTRAINT uc_tokens_token UNIQUE (token);

ALTER TABLE client_linked_accounts
    ADD CONSTRAINT fk_client_linked_accounts_on_client FOREIGN KEY (client_id) REFERENCES clients (id);